# Generated by Django 5.1.7 on 2025-04-01 02:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parkingbooking_parkingslot_delete_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='parkingslot',
            old_name='slot_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='slot_type',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium'), ('disabled', 'Disabled'), ('electric', 'Electric Charging')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkingslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingBooking',
        ),
    ]
